# Generated by Django 4.2.16 on 2024-11-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(db_column='Categorie', max_length=100)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categories_of_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_on_sell', models.IntegerField(db_column='Cost_on_sell')),
                ('cost_on_buy', models.IntegerField(db_column='Cost_on_buy')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('quantity_on_stock', models.IntegerField(db_column='Quantity_on_stock')),
                ('picture', models.ImageField(max_length=255, upload_to='main/img/')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saeles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'saeles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=30, null=True)),
                ('pasword', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'SiteUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'trashbox',
                'managed': False,
            },
        ),
    ]
